name: flutter_tt
description: Flutter project for teamtalk.


version: 1.0.0+1

environment:
  sdk: '>=2.6.0-dev.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: any
  protobuf: ^0.13.0
  convert: any
  crypto: any
  pointycastle: any
  sqflite: any
  path_provider: any
  shared_preferences: any
  event_bus: any
  toast: any
  image_picker:
    git: https://github.com/xiaominfc/image_picker.git
  dio: any
  teamtalk_dart_lib:
      path: ../teamtalk_dart_lib/

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true
  assets:
    - images/
    - images/yaya/